---
# Mappings are used to map the generic packages name used to define projects
# to the specific package names used by each OS. They implement inheritance,
# so you can define them without repeating yourself too much.
#
# Inheritance works the way you'd expect, that is, in order of increasing
# priority:
#
#   - default
#   - package format (deb, pkg, rpm)
#   - OS name (CentOS, Debian, Fedora, FreeBSD, Ubuntu)
#   - OS version (CentOS6, Debian9, FedoraRawhide, Ubuntu14 and so on)
#
# So something like
#
#   make:
#     default: make
#     FreeBSD: gmake
#
# will result in the 'make' package being installed everywhere except
# for FreeBSD, where 'gmake' will be used instead. Clearing out existing
# mappings is possible as well, so
#
#   ccache:
#     default: ccache
#     CentOS:
#
# will result in the 'ccache' package being installed everywhere except
# for CentOS, where nothing will be installed.

mappings:

  apparmor:
    deb: libapparmor-dev

  augeas:
    default: augeas
    deb: augeas-tools

  autoconf:
    default: autoconf

  automake:
    default: automake

  autopoint:
    deb: autopoint
    pkg: gettext-tools
    rpm: gettext-devel

  avahi:
    deb: libavahi-client-dev
    pkg: avahi
    rpm: avahi-devel

  ccache:
    default: ccache
    CentOS:

  check:
    default: check
    rpm: check-devel

  cppi:
    Fedora: cppi
    FreeBSD: cppi

  cyrus-sasl:
    deb: libsasl2-dev
    pkg: cyrus-sasl
    rpm: cyrus-sasl-devel

  device-mapper:
    deb: libdevmapper-dev
    rpm: device-mapper-devel

  dnsmasq:
    default: dnsmasq
    deb: dnsmasq-base

  dtrace:
    deb: systemtap-sdt-dev
    rpm: systemtap-sdt-devel

  ebtables:
    default: ebtables
    FreeBSD:

  fuse:
    deb: libfuse-dev
    pkg: fusefs-libs
    rpm: fuse-devel

  gcc:
    default: gcc
    FreeBSD:

  gettext:
    default: gettext

  glib2:
    deb: libglib2.0-dev
    pkg: glib
    rpm: glib2-devel

  glibc:
    deb: libc6-dev
    rpm: glibc-devel

  glibc-static:
    deb: libc6-dev
    rpm: glibc-static

  glusterfs:
    deb: glusterfs-client
    pkg: glusterfs
    rpm: glusterfs-api-devel

  gnome-common:
    default: gnome-common

  gnutls:
    deb: libgnutls28-dev
    pkg: gnutls
    rpm: gnutls-devel
    Ubuntu12: libgnutls-dev
    Ubuntu14: libgnutls-dev

  go:
    default: golang
    FreeBSD: go
    CentOS6:
    Ubuntu12:
    Ubuntu14:

  gobject-introspection:
    deb: libgirepository1.0-dev
    pkg: gobject-introspection
    rpm: gobject-introspection-devel
    CentOS6:

  gtk-doc:
    default: gtk-doc
    deb: gtk-doc-tools

  hal:
    FreeBSD: hal
    Ubuntu12: libhal-dev

  intltool:
    default: intltool

  iscsiadm:
    deb: open-iscsi
    rpm: iscsi-initiator-utils

  libacl:
    deb: libacl1-dev
    rpm: libacl-devel

  libarchive:
    deb: libarchive-dev
    pkg: libarchive
    rpm: libarchive-devel

  libattr:
    deb: libattr1-dev
    rpm: libattr-devel

  libaudit:
    deb: libaudit-dev
    rpm: audit-libs-devel

  libblkid:
    deb: libblkid-dev
    rpm: libblkid-devel

  libcap-ng:
    deb: libcap-ng-dev
    rpm: libcap-ng-devel

  libcmpiutil:
    rpm: libcmpiutil-devel

  libconfig:
    deb: libconfig-dev
    pkg: libconfig
    rpm: libconfig-devel

  libcurl:
    deb: libcurl4-gnutls-dev
    pkg: curl
    rpm: libcurl-devel

  libdbus:
    deb: libdbus-1-dev
    pkg: dbus
    rpm: dbus-devel

  libnl:
    CentOS6: libnl-devel

  libnl3:
    deb: libnl-3-dev
    rpm: libnl3-devel

  libnlroute3:
    deb: libnl-route-3-dev
    rpm: libnl3-devel

  libnuma:
    deb: libnuma-dev
    rpm: numactl-devel

  libparted:
    deb: libparted-dev
    rpm: parted-devel

  libpcap:
    deb: libpcap-dev
    pkg: libpcap
    rpm: libpcap-devel

  libpciaccess:
    deb: libpciaccess-dev
    pkg: libpciaccess
    rpm: libpciaccess-devel

  librbd:
    deb: librbd-dev
    Fedora: librbd-devel
    CentOS7: librbd1-devel

  libselinux:
    deb: libselinux1-dev
    rpm: libselinux-devel

  libsoup:
    deb: libsoup2.4-dev
    pkg: libsoup
    rpm: libsoup-devel

  libssh:
    pkg: libssh
    rpm: libssh-devel
    Debian: libssh-gcrypt-dev
    Ubuntu: libssh-dev
    CentOS6:

  libssh2:
    deb: libssh2-1-dev
    pkg: libssh2
    rpm: libssh2-devel

  libtool:
    default: libtool
    Debian: libtool-bin
    Ubuntu16: libtool-bin

  libtoolize:
    default: libtool

  libudev:
    deb: libudev-dev
    rpm: libudev-devel

  libuuid:
    deb: uuid-dev
    pkg: e2fsprogs-libuuid
    rpm: libuuid-devel

  libxml2:
    deb: libxml2-dev
    pkg: libxml2
    rpm: libxml2-devel

  libxslt:
    deb: libxslt1-dev
    pkg: libxslt
    rpm: libxslt-devel

  lvm2:
    default: lvm2
    FreeBSD:

  make:
    default: make
    FreeBSD: gmake

  mingw32-curl:
    FedoraRawhide: mingw32-curl

  mingw32-dbus:
    FedoraRawhide: mingw32-dbus

  mingw32-dlfcn:
    FedoraRawhide: mingw32-dlfcn

  mingw32-gcc:
    FedoraRawhide: mingw32-gcc

  mingw32-gettext:
    FedoraRawhide: mingw32-gettext

  mingw32-gnutls:
    FedoraRawhide: mingw32-gnutls

  mingw32-libssh2:
    FedoraRawhide: mingw32-libssh2

  mingw32-libxml2:
    FedoraRawhide: mingw32-libxml2

  mingw32-openssl:
    FedoraRawhide: mingw32-openssl

  mingw32-pkg-config:
    FedoraRawhide: mingw32-pkg-config

  mingw32-portablexdr:
    FedoraRawhide: mingw32-portablexdr

  mingw32-readline:
    FedoraRawhide: mingw32-readline

  mingw64-curl:
    FedoraRawhide: mingw64-curl

  mingw64-dbus:
    FedoraRawhide: mingw64-dbus

  mingw64-dlfcn:
    FedoraRawhide: mingw64-dlfcn

  mingw64-gcc:
    FedoraRawhide: mingw64-gcc

  mingw64-gettext:
    FedoraRawhide: mingw64-gettext

  mingw64-gnutls:
    FedoraRawhide: mingw64-gnutls

  mingw64-libssh2:
    FedoraRawhide: mingw64-libssh2

  mingw64-libxml2:
    FedoraRawhide: mingw64-libxml2

  mingw64-openssl:
    FedoraRawhide: mingw64-openssl

  mingw64-pkg-config:
    FedoraRawhide: mingw64-pkg-config

  mingw64-portablexdr:
    FedoraRawhide: mingw64-portablexdr

  mingw64-readline:
    FedoraRawhide: mingw64-readline

  netcf:
    deb: libnetcf-dev
    rpm: netcf-devel

  numad:
    default: numad
    FreeBSD:
    Debian8:
    Ubuntu12:
    Ubuntu14:

  openwsman:
    rpm: libwsman-devel
    Ubuntu: libopenwsman-dev

  parted:
    default: parted
    FreeBSD:

  patch:
    default: patch

  pci-ids:
    default: hwdata
    FreeBSD: pciids

  perl:
    default: perl
    FreeBSD: perl5

  perl-CPAN-Changes:
    deb: libcpan-changes-perl
    pkg: p5-CPAN-Changes
    rpm: perl-CPAN-Changes
    CentOS6:

  perl-Config-Record:
    deb: libconfig-record-perl
    pkg: p5-Config-Record
    Fedora: perl-Config-Record

  perl-Digest:
    deb: libdigest-perl
    pkg: p5-Digest
    rpm: perl-Digest
    CentOS6:

  perl-Digest-MD5:
    deb: libdigest-perl-md5-perl
    pkg: p5-Digest-MD5
    rpm: perl-Digest-MD5
    CentOS6:
    Ubuntu12:
    Ubuntu14:

  perl-ExtUtils-MakeMaker:
    deb: perl-modules
    pkg: p5-ExtUtils-MakeMaker
    rpm: perl-ExtUtils-MakeMaker

  perl-File-Slurp:
    deb: libfile-slurp-perl
    pkg: p5-File-Slurp
    rpm: perl-File-Slurp

  perl-IO-Compress-Bzip2:
    deb: libio-compress-perl
    pkg: p5-IO-Compress
    rpm: perl-IO-Compress-Bzip2

  perl-IO-String:
    deb: libio-string-perl
    pkg: p5-IO-String
    rpm: perl-IO-String

  perl-Module-Build:
    deb: libmodule-build-perl
    pkg: p5-Module-Build
    rpm: perl-Module-Build

  perl-Sub-Uplevel:
    deb: libsub-uplevel-perl
    pkg: p5-Sub-Uplevel
    rpm: perl-Sub-Uplevel

  perl-TAP-Formatter-HTML:
    deb: libtap-formatter-html-perl
    Fedora: perl-TAP-Formatter-HTML

  perl-TAP-Formatter-JUnit:
    deb: libtap-formatter-junit-perl
    pkg: p5-TAP-Formatter-JUnit
    Fedora: perl-TAP-Formatter-JUnit

  perl-TAP-Harness-Archive:
    deb: libtap-harness-archive-perl
    Fedora: perl-TAP-Harness-Archive

  perl-Test-Exception:
    deb: libtest-exception-perl
    pkg: p5-Test-Exception
    rpm: perl-Test-Exception

  perl-Test-LWP-UserAgent:
    deb: libtest-lwp-useragent-perl
    pkg: p5-Test-LWP-UserAgent
    Fedora: perl-Test-LWP-UserAgent
    Ubuntu12:

  perl-Test-Pod:
    deb: libtest-pod-perl
    pkg: p5-Test-Pod
    rpm: perl-Test-Pod

  perl-Test-Pod-Coverage:
    deb: libtest-pod-coverage-perl
    pkg: p5-Test-Pod-Coverage
    rpm: perl-Test-Pod-Coverage

  perl-Time-HiRes:
    deb: libtime-hr-perl
    pkg: p5-Time-HiRes
    rpm: perl-Time-HiRes
    Ubuntu12: perl
    Ubuntu14: perl

  perl-XML-Twig:
    deb: libxml-twig-perl
    pkg: p5-XML-Twig
    rpm: perl-XML-Twig

  perl-XML-Writer:
    deb: libxml-writer-perl
    pkg: p5-XML-Writer
    rpm: perl-XML-Writer

  perl-XML-XPath:
    deb: libxml-xpath-perl
    pkg: p5-XML-XPath
    rpm: perl-XML-XPath

  perl-accessors:
    deb: libaccessors-perl
    pkg: p5-accessors
    Fedora: perl-accessors

  pkg-config:
    default: pkgconf
    rpm: pkgconfig
    Ubuntu12: pkg-config

  polkit:
    deb: policykit-1
    pkg: polkit
    rpm: polkit-devel

  python2-devel:
    deb: python-dev
    pkg: python27
    rpm: python2-devel

  python2-lxml:
    default: python-lxml
    Fedora: python2-lxml
    FreeBSD: py27-lxml

  python2-nose:
    default: python-nose
    Fedora: python2-nose
    FreeBSD: py27-nose

  python3-devel:
    deb: python3-dev
    pkg: python36
    Fedora: python3-devel

  python3-lxml:
    default: python3-lxml
    FreeBSD: py36-lxml
    CentOS:

  python3-nose:
    default: python3-nose
    FreeBSD: py36-nose
    CentOS:

  qemu-img:
    default: qemu-utils
    rpm: qemu-img

  radvd:
    default: radvd

  readline:
    deb: libreadline-dev
    pkg: readline
    rpm: readline-devel

  rpmbuild:
    rpm: rpm-build

  sanlock:
    deb: libsanlock-dev
    rpm: sanlock-devel
    Ubuntu12:

  scrub:
    default: scrub
    FreeBSD: diskscrub

  sheepdog:
    default: sheepdog
    CentOS:
    FreeBSD:

  showmount:
    deb: nfs-common
    rpm: nfs-utils

  usb-ids:
    default: hwdata
    FreeBSD: usbids

  vala:
    default: vala
    deb: valac
    CentOS6:

  wget:
    default: wget

  wireshark:
    deb: wireshark-dev
    Fedora: wireshark-devel
    Debian8:
    Ubuntu12:
    Ubuntu14:

  xen:
    deb: libxen-dev
    Fedora: xen-devel

  xmllint:
    default: libxml2
    deb: libxml2-utils

  xsltproc:
    default: libxslt
    deb: xsltproc

  xz:
    deb: liblzma-dev
    rpm: xz-devel

  xz-static:
    deb: liblzma-dev
    Fedora: xz-static

  yajl:
    deb: libyajl-dev
    pkg: yajl
    rpm: yajl-devel

  zfs:
    default: zfs-fuse
    CentOS:
    FreeBSD:

  zlib:
    deb: zlib1g-dev
    rpm: zlib-devel

  zlib-static:
    deb: zlib1g-dev
    rpm: zlib-static
