---
ansible_python_interpreter: /usr/local/bin/python2

bash: /usr/local/bin/bash
java: /usr/local/bin/java
make: /usr/local/bin/gmake
sudo: /usr/local/bin/sudo

projects:
  - base
  - jenkins
  - libosinfo
  - libvirt
  - libvirt-glib
  - libvirt-go
  - libvirt-go-xml
  - libvirt-perl
  - libvirt-python
  - libvirt-tck
  - osinfo-db
  - osinfo-db-tools
  - virt-manager
  - virt-viewer

jenkins_secret: '{{ vault.jenkins_secret }}'
